# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CoworkMdm < Formula
  desc "Claude Desktop enterprise deployment toolkit — MDM config profiles,
plugin marketplace management, and per-host diagnostics.
"
  homepage "https://github.com/krislavten/cowork-mdm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krislavten/cowork-mdm/releases/download/v0.3.1/cowork-mdm_0.3.1_darwin_x86_64.tar.gz"
      sha256 "5f71df5463bc925641e0da5ffb65121d43a0fd712a620968923185cffe7b8d25"

      define_method(:install) do
        bin.install "cowork-mdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krislavten/cowork-mdm/releases/download/v0.3.1/cowork-mdm_0.3.1_darwin_arm64.tar.gz"
      sha256 "adf18bbfadfb9e45d6246db826c51b9a4538f37dc703fcf0f23d85af8424ddcc"

      define_method(:install) do
        bin.install "cowork-mdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krislavten/cowork-mdm/releases/download/v0.3.1/cowork-mdm_0.3.1_linux_x86_64.tar.gz"
      sha256 "9226846ecb6f80eb041b0617470343d3e5acc803815c42f1016e972b7e774380"
      define_method(:install) do
        bin.install "cowork-mdm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krislavten/cowork-mdm/releases/download/v0.3.1/cowork-mdm_0.3.1_linux_arm64.tar.gz"
      sha256 "21a9c7b4eb8c0fb1e53f06e57bd87dabd7a029d8c36a275df605855eccbcba6e"
      define_method(:install) do
        bin.install "cowork-mdm"
      end
    end
  end

  test do
    system "#{bin}/cowork-mdm --version"
  end
end
